"""Add price_forecasts table

Revision ID: 8689ea9d482c
Revises: e0912788401e
Create Date: 2026-08-28 18:58:11.935975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8689ea9d482c'
down_revision: Union[str, Sequence[str], None] = 'e0912788401e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('price_forecasts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('base_price', sa.Float(), nullable=False),
    sa.Column('vix_value', sa.Float(), nullable=False),
    sa.Column('pred_1d_10th', sa.Float(), nullable=False),
    sa.Column('pred_1d_50th', sa.Float(), nullable=False),
    sa.Column('pred_1d_90th', sa.Float(), nullable=False),
    sa.Column('pred_1m_10th', sa.Float(), nullable=False),
    sa.Column('pred_1m_50th', sa.Float(), nullable=False),
    sa.Column('pred_1m_90th', sa.Float(), nullable=False),
    sa.Column('pred_3m_10th', sa.Float(), nullable=False),
    sa.Column('pred_3m_50th', sa.Float(), nullable=False),
    sa.Column('pred_3m_90th', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_price_forecasts_id'), 'price_forecasts', ['id'], unique=False)
    op.create_index(op.f('ix_price_forecasts_symbol'), 'price_forecasts', ['symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_price_forecasts_symbol'), table_name='price_forecasts')
    op.drop_index(op.f('ix_price_forecasts_id'), table_name='price_forecasts')
    op.drop_table('price_forecasts')
    # ### end Alembic commands ###
